export interface Challan {
  id?: number; // Optional for new entries, will be generated by backend
  name: string;
  mobile: string;
  vehicleType: string;
  plateNumber: string;
  startTime: string; // Can be adjusted to a Date type if needed
  endTime: string; // Can be adjusted to a Date type if needed
  violationTime?: string; // Optional until calculated
  amount: number;
  status: string; // Can be 'Paid' or 'Unpaid'
}
